[milesmcc]
name = "Miles McCain"
website = "https://miles.land"
github = "milesmcc"
email = "privacyspy@sendmiles.email"
role = "founder"

[ibarakaiev]
name = "Igor Barakaiev"
website = "https://igor.fyi"
github = "ibarakaiev"
email = "privacyspy@igor.fyi"
role = "founder"

[doamatto]
name = "Matt"
website = "https://doamatto.xyz"
github = "doamatto"