category = "transparency"
slug = "history"
text = "Is the policy's history made available?" 
notes = []
points = 5

[[options]]
id = "no"
text = "No"
percent = 0

[[options]]
id = "last-modified"
text = "Only the date it was last modified"
percent = 50

[[options]]
id = "yes"
text = "Yes, with revisions or a changelog"
percent = 100
