name = "Adobe"
description = "Adobe is changing the world through digital experiences. We help our customers create, deliver, and optimize content and applications."
slug = "adobe"
hostnames = [ "adobe.com" ]
sources = [ "https://www.adobe.com/privacy/policy.html" ]
contributors = [ "UnKnOwN" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "Adobe runs online ad campaigns that display ads for you based on your likely interests. We may learn your likely interests when you use our apps and websites. We also acquire information from other companies that gives us more insight about your likely interests based on your activity on non-Adobe web pages and mobile apps. These types of ads are often called “interest-based ads” or “online behavioral advertising.” We use ad platforms to display Adobe ads on non-Adobe web pages and in non-Adobe apps.\"\n\"If you prefer that we do not deliver web ads to you based on how you use Adobe apps and websites, please tell us not to deliver Adobe interest-based ads to you.\n\nIf you prefer that we not deliver ads to you in non-Adobe apps based on how you use Adobe apps and websites, please set the preference on your mobile device to limit ad tracking."
]

[rubric.security]
value = "somewhat"
citations = [
  "We provide reasonable administrative, technical, and physical security controls to protect your personal information. However, despite our efforts, no security controls are 100% effective and Adobe cannot ensure or warrant the security of your personal information."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "To help keep our databases current and to provide you the most relevant content and experiences, we may combine information provided by you with information from third party sources, in accordance with applicable law. "
]

[rubric.history]
value = "last-modified"
notes = [
  "The last modified date is available at the top of the policy."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "Under the law of some countries, you may have the right to ask us for a copy of your personal information; to correct, delete or restrict (stop any active) processing of your personal information; and to obtain the personal information you provide to us for a contract or with your consent in a structured, machine readable format, and to ask us to share (port) this information to another controller."
]

[rubric.data-breaches]
value = "no"
notes = [
  "Nothing is mentioned about data breaches in the privacy policy. "
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "The types of third parties your information may be shared with include, our resellers and other sales and advertising partners, retailers, research organizations, advertisers, ad agencies, advertising networks and platforms, information service providers, publishers, and non-profit organizations (with your consent, if required).\n\nWe will share personal information with companies, organizations or individuals outside of Adobe if we have a good-faith belief that access, use, preservation or disclosure of the information is reasonably necessary to detect, prevent, or otherwise address fraud, security or technical issues, as well as to protect against harm to the rights, property or safety of Adobe, our users, or the public as required or permitted by law."
]

[rubric.data-collection-reasoning]
value = "mostly"
notes = [
  "The service does a good job in explaining the purposes for data collecting, however, not all data types are accompanied by a clear explanation. "
]

[rubric.noncritical-purposes]
value = "opt-out-all"
notes = [
  "You can opt-out from sharing the information about Desktop/Mobile Applications, participation in the Adobe Experience Cloud Device Co-op and also stop the Machine learning analysis on your content. However, your data can still be used for other non-critical purposes (for example for diagnosing problems in apps and websites)."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "Adobe may also share your personal information: [...]\nWhen we are required to provide information in response to a subpoena, court order, or other applicable law or legal process."
]

[rubric.list-collected]
value = "generally"
notes = [
  "The privacy policy lists of data it collects very specifically, though there are few \"such as\" phrases. "
]

[rubric.revision-notify]
value = "yes"
citations = [
  "If we do, the links to the policy on our websites (which are generally found in the footer of the website) will indicate that the policy has been changed. For new users, the change will become effective upon posting. For existing users, if the change is significant, it will become effective 30 days after posting. We encourage you to periodically review the Adobe Privacy Center for the latest information on our privacy practices."
]
