name = "DomeinDNS"
description = "DomeinDNS offers a DNS service."
slug = "domeindns"
hostnames = [ "domeindns.nl" ]
sources = [ "https://app.domeindns.nl/legal/privacy" ]
contributors = [ "Jelle" ]

[rubric.behavioral-marketing]
value = "no"

[rubric.security]
value = "somewhat"

[rubric.third-party-collection]
value = "no"

[rubric.history]
value = "last-modified"

[rubric.data-deletion]
value = "yes-contact"

[rubric.data-breaches]
value = "no"

[rubric.third-party-access]
value = "no"

[rubric.data-collection-reasoning]
value = "yes"

[rubric.noncritical-purposes]
value = "na"

[rubric.law-enforcement]
value = "strict"

[rubric.list-collected]
value = "exhaustively"

[rubric.revision-notify]
value = "yes"
