name = "eNom"
description = "Enom, Inc. is a domain name registrar and Web hosting company that also sells other products closely tied to domain names, such as SSL certificates, e-mail services, and Website building software."
slug = "enom"
hostnames = [ "enom.com" ]
sources = [ "https://www.enom.com/terms/privacy.aspx" ]
contributors = [ "doamatto" ]

[rubric.behavioral-marketing]
value = "yes-opt-out"
citations = [
  "In some cases, users’ non-personal information and data may be automatically collected through the standard operation of Enom’s Internet servers or through the use of “cookies”. “Cookies” are small text files that are used by websites to: (a) recognize repeat users; (b) track usage behavior; and (c) compile aggregate data that will permit content improvements and targeted advertising. Enom cannot control or prevent the use of cookies or any information obtained through such cookies by advertisers or third parties. If you do not want information collected through the use of cookies, most browsers permit you to disable the cookie feature. However, cookies may be required for the use of certain features on the Websites."
]

[rubric.security]
value = "somewhat"
citations = [
  "Enom shall protect personal information by implementing security safeguards appropriate to the sensitivity of the information.\n\nEnom shall protect personal information against such risks as loss, theft, unauthorized access, disclosure, copying, use, modification, or destruction, through appropriate security measures. Enom shall protect the information regardless of the format in which it is held.\nEnom shall protect personal information it discloses to third parties by contractual agreements stipulating the confidentiality of the information and the purposes for which it is to be used.\nAll of Enom’s employees with access to personal information shall be required as a condition of employment to contractually respect the confidentiality of personal information."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "Enom may also collect personal information from other sources including but not limited to credit bureaus or other third parties who represent that they have the right to disclose the information."
]

[rubric.history]
value = "last-modified"
citations = [ "  14 October 2019" ]

[rubric.data-deletion]
value = "no"
notes = [
  "This policy doesn't require the service to let you delete your data."
]

[rubric.data-breaches]
value = "no"
notes = [
  "This policy doesn't require the service to alert you in the event of a data breach."
]

[rubric.third-party-access]
value = "yes-unspecified"
citations = [
  "1) Enom may disclose a customer’s personal information to: [...] A third party service provider for the efficient and cost-effective provision of services purchased through the Websites; [...] An agent or third party retained by Enom in connection with Enom’s administration or the provision of Enom’s products or services; [...] A third party or parties, where the customer consents to such disclosure or disclosure is required by law or emergency."
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "In obtaining consent, Enom shall use reasonable efforts to ensure that a customer is advised of the identified purposes for which personal information collected will be used or disclosed. Purposes shall be stated in a manner that can be reasonably understood by the customer or employee.\nGenerally, Enom shall seek consent to use and disclose personal information at the same time it collects the information. However, Enom may seek consent to use and disclose personal information after it has been collected but before it is used or disclosed for a new purpose.\nEnom will only require customers to consent to the collection, use, or disclosure of personal information as a condition to the supply of a product or service if such collection, use, or disclosure is required to fulfill the identified purposes.\nIn determining the appropriate form of consent, Enom shall take into account the sensitivity of the personal information and the reasonable expectations of its customers.\nUnless required by contract, Enom will obtain express consent within a reasonable period after obtaining the data and prior to using the data.\nA customer may withdraw consent at any time, subject to legal, regulatory, or contractual restrictions and reasonable notice. For example, if consent is required to perform the service requested by the customer, withdrawal of consent may result in termination of the service. Customers may contact Enom at the address below for more information regarding the implications of doing so."
]

[rubric.noncritical-purposes]
value = "no"
notes = [
  "There are no instances where a user can opt-out of data being used for non-critical purposes"
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "Enom shall not use or disclose personal information for purposes other than those for which it was collected, except with the consent of the individual or as required by a registry or by law. Enom shall retain personal information only as long as necessary for the fulfillment of those purposes or as required by law."
]

[rubric.list-collected]
value = "summarily"
citations = [
  "Enom shall identify the purposes for which personal information is collected within a reasonable period after obtaining the data, and prior to using the data.\n\nEnom collects personal information only for the following purposes:\nTo establish and maintain responsible commercial relations with customers and to provide ongoing services and offers;\nTo understand customer needs;\nTo develop, enhance, market, or provide products and services;\nTo manage and develop Enom’s business and operations, including personnel and employment matters; and\nTo meet legal, regulatory, and contractual requirements.\nFurther references to “identified purposes” mean the purposes identified in this Principle 2.\nEnom shall specify orally, electronically, or in writing the identified purposes to the customer or employee at the time personal information is collected or within a reasonable period. Upon request, persons collecting personal information shall explain these identified purposes or refer the individual to a designated person within Enom who shall explain the purposes.\nUnless required by law, Enom shall not use or disclose for any new purpose personal information that has been collected without first identifying and documenting the new purpose and obtaining the consent of the customer."
]

[rubric.revision-notify]
value = "no"
notes = [
  "This policy can change without the service being required to let you know about such."
]
