name = "MSN"
description = "Portal for shopping, news and money, e-mail, search, and chat.\t"
slug = "msn"
hostnames = [ "msn.com" ]
sources = [ "https://www.msn.com/en-us/autos/partner/privacypolicy" ]
contributors = [ "UnKnOwN" ]

[rubric.behavioral-marketing]
value = "yes"
citations = [
  "We use third parties to serve some or all of the advertisements that are placed within our sites and they may use information (not including personally identifiable information) about your visits to our sites and other sites to assist in serving advertisements to you. These companies may employ cookies, web beacons, and action tags to measure advertising effectiveness. They may share anonymous information with their clients such as date/time of the banner ad shown, the specific ad shown, the IP address, etc."
]

[rubric.security]
value = "yes"
citations = [
  "We use Secure Socket Layer (SSL) technology to encrypt important information, such as your credit card data, in an effort to prevent unauthorized access during transmission of your orders over the Internet. We incorporate standard industry practices suitable to the degree of sensitivity of the information involved to maintain the security of your personal information and to avoid its disclosure except as described in this policy. Your personal information may also be protected by the password you created when you registered at one of our websites where this feature is offered."
]

[rubric.third-party-collection]
value = "yes"
citations = [
  "Our websites automatically collect certain information, such as your IP address, browser type, domain name, access times and referring website address."
]

[rubric.history]
value = "last-modified"
notes = [
  "The last modified date is available at the top of the policy."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "You also may write to us directly if you wish to: update or delete your contact information."
]
notes = [
  "It can be inferred that you can fully delete your personal data by contacting someone."
]

[rubric.data-breaches]
value = "no"
notes = [
  "Nothing is mentioned about data breaches in the privacy policy."
]

[rubric.third-party-access]
value = "yes-unspecified"
notes = [
  "The privacy policy lists the general groups of companies it shares your personal information with, however, does not specify all the companies. "
]

[rubric.data-collection-reasoning]
value = "mostly"
citations = [
  "We use the personal information you provide to allow you to make product purchases, to fulfill your requests, improve our publications, products and services, to send you promotional offers related to TEN or our business partners, and to operate our business. A user may, at any time, opt out of receiving promotional offers by mail or e-mail. How You Can Control Your Personal Information. We also use collected information to evaluate and administer our products and services, respond to any problems that may arise, such as magazine delivery failures, difficulties in navigating our sites or accessing certain features, as well as to gauge user trends to determine what products and services are most popular with users, and to put you in touch with fulfillment partners who can provide services that we cannot. We allow users of our website to send articles or links by e-mail to other parties who may be interested in them. We do not retain any e-mail addresses of either the sender or recipient of such articles or links after they are sent, and do not share “send a friend” e-mail addresses with third parties."
]
notes = [
  "MSN clearly explains why it collects personal data. However, the reasons why the company collects data is not clearly explained for exactly each piece of data."
]

[rubric.noncritical-purposes]
value = "opt-out-some"
citations = [
  "We may share your personal information with third parties, such as advertisers, sponsors, and other promotional and business partners, only when you have not opted out of receiving communications from third parties. "
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "We reserve the right to use or disclose any information without notice or consent as needed to satisfy any law, regulation or legal request."
]

[rubric.list-collected]
value = "generally"
citations = [
  "Personal Information. We collect personally identifiable information, such as names, mailing addresses, e-mail addresses, demographic information, and similar information in a variety of situations, including but not limited to the following: (i) when you subscribe to one of our magazines or place an order (see the section below for more information on subscriptions and orders); (ii) when you register at one of our websites in connection with the purchase of a product, publication, or service; (iii) when you enter personal information on one of our websites as a condition of participating in contests, promotions, or sweepstakes offered via these websites; or (iv) when you wish to have a product or service fulfilled by a fulfillment partner who can meet the continuing needs of our customers.\n\nSome of our sites may collect credit card and related financial information if you wish to purchase a product or subscribe to any publication or service offered via these sites. If you wish to subscribe to one of our publications or place an order for products or services online, you must generally establish a credit card account with us or our vendors. Some of our sites also may collect social security numbers from consumers if such consumers use one of our automotive-related websites and wish to receive a quote from an automotive lender that is part of the site’s automotive lender network. In such instances, we collect social security numbers only to fulfill consumers’ requests to receive quotes or other financial offers from a lender in the site’s automotive lender network.\n\nInformation Collected Automatically. Our websites automatically collect certain information, such as your IP address, browser type, domain name, access times and referring website address. This helps facilitate your online experience at our websites. See Sections IV and V of this Privacy Policy for more detail on cookies, web beacons, and other information collected automatically by our websites."
]
notes = [
  "The site explains the information it collects generally well, however uses some \"such as\" phrases which make the statements non-absolute."
]

[rubric.revision-notify]
value = "no"
citations = [
  "We will occasionally update this Privacy Policy as necessary to protect our users and to comply with a changing environment. We recommend that you check the posted Privacy Policy when you visit any of our sites to be sure you are aware of and understand our current policy. Your continued use of the respective site means you accept the updated Privacy Policy."
]
notes = [
  "You have to check the privacy policy and you will not be notified when it's changed."
]
