name = "SamoChat"
description = "A social media platform built to protect people's privacy"
slug = "samochat"
hostnames = [ "samochat.net" ]
sources = [ "https://samochat.net/pages/privacy" ]
contributors = [ "newuser_PMi0H" ]

[rubric.behavioral-marketing]
value = "no"

[rubric.security]
value = "yes"

[rubric.third-party-collection]
value = "no"

[rubric.history]
value = "no"

[rubric.data-deletion]
value = "yes-automated"

[rubric.data-breaches]
value = "na"

[rubric.third-party-access]
value = "no"

[rubric.data-collection-reasoning]
value = "yes"

[rubric.noncritical-purposes]
value = "na"

[rubric.list-collected]
value = "exhaustively"

[rubric.revision-notify]
value = "yes"
