name = "Surfshark"
description = "A VPN Provider"
slug = "surfshark"
hostnames = [ "https://surfshark.com" ]
sources = [ "https://surfshark.com/privacy-policy" ]
contributors = [ "Donno" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "As you probably already understood we do not have much information to share. Even so, we do not disclose your information to others, unless we are ordered by a court of competent jurisdiction to do so. We do not sell or trade your data with anyone."
]
notes = [
  "Only on the website:\n\n2. How does our Website interact with third party services and content?\nStorage ad infrastructure providers and Ads service providers – they help us to deliver targeted advertising to the Website visitors."
]

[rubric.security]
value = "somewhat"
citations = [
  "8. How do we secure your information?\n\nWe have implemented various security measures, including SSL/TLS encryption for data transfers, hashed passwords, firewalls, and regular audits. We take all steps reasonably necessary to ensure that your data is treated securely.\n\nWhile we implement security measures on our Website and through our Services, you should be aware that 100% security is not always possible. Whenever you give out your information online there is a risk that a third party may intercept and use that information. While we strive to protect your information and privacy, we cannot guarantee the security of any information you disclose online. By using the Services, you expressly acknowledge and agree that we cannot guarantee the security of any data provided to or received by us through the Services and that any general information, other data or information received from you through the Website or our Services is provided at your own responsibility."
]

[rubric.history]
value = "last-modified"
citations = [
  "13. When was this policy last updated?\nKeep in mind that we can update this Policy in the future & check it regularly.\nMay 4, 2020."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "If you would like to edit your information or permanently delete your account, you can email us at support@surfshark.com.\n\nIf you request, we will delete your information specified in Clause 1, unless, we are legally required to maintain certain personal data, including situations such as the following:\n\n- If there is an unresolved issue relating to your account, such as an outstanding credit on your account or an unresolved claim or dispute we will retain the necessary information about you until the issue is resolved;\n\n- Where we are required to retain the information about you for our legal, tax, audit, and accounting obligations, we will retain only the necessary information for the period required by applicable law; and/or,\n\n- Where necessary for our legitimate business interests such as fraud prevention or to maintain the security of our users.\n"
]

[rubric.data-breaches]
value = "no"
citations = [ "(Not specified)" ]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "To fully use Surfshark Services, you will need to create a user account. We collect the following information provided upon signup:\n\n-User’s e-mail address and encrypted password. We need your email address to create and manage your account, to provide customer service, whether it’s responding to a request or following up on an order, and to market products and Services that may be of interest to you.\n\n-Basic billing information and order history. We collect only the basic billing information (e. g. payment amount, currency, date of the payment) and order history to process your orders and to comply with applicable legal requirements. We also support anonymous payment methods (you can purchase the Services with cryptocurrency). If you make payments using our third-party payment service providers, all payment data you provide will rest with them."
]

[rubric.noncritical-purposes]
value = "na"
citations = [
  "Can’t share much when you don’t really collect anything beyond what’s strictly necessary. We strictly do not disclose what little we do have, unless a court may order us to (our Warrant Canary page will display if we’re ever asked to do so)."
]

[rubric.law-enforcement]
value = "strict"
citations = [
  "We do not disclose your information to others, unless we are ordered by a court of competent jurisdiction to do so. "
]

[rubric.list-collected]
value = "exhaustively"
citations = [
  "What information is collected?\n\nPersonal Information:\nWe do need to keep the information you provide when you’re creating your account, though. Usually we ask for your email address and basic billing information. It’s the only way we can make sure your account works.\n\nDiagnostics\nIf our apps misbehave, we’d appreciate a diagnostics report (it shows us what went wrong without giving away anything about you or what you do online). You can opt out, but it helps us fix any issues much more efficiently. \n\n\nInformation we collect on our Website and apps\nWe use tools like Google Analytics to keep our website working and to do marketing. You can opt out of this, too - but on Google’s terms. We also use advertising IDs in our apps (you can opt out on your device). Simply said, these also don’t give away anything about you personally or about what you do online. It merely allows us to, for example, show ads to people who have visited our website before or to see that something on our site doesn’t work quite as it should. "
]
