name = "Taobao"
description = "Taobao Marketplace is the online shopping destination of choice for Chinese consumers looking for wide selection, value and convenience."
slug = "taobao"
hostnames = [ "taobaonline.com" ]
sources = [ "https://www.taobaonline.com/privacy-policy/" ]
contributors = [ "UnKnOwN" ]

[rubric.behavioral-marketing]
value = "no"
notes = [
  "Nothing is mentioned about personally-targeted marketing in the privacy policy and it can be reasonably inferred that the site does not use it."
]

[rubric.security]
value = "no"
notes = [
  "Nothing is mentioned about security practices in the privacy policy."
]

[rubric.third-party-collection]
value = "no"
notes = [
  "Nothing is mentioned about collecting of personal data from third parties."
]

[rubric.history]
value = "no"
notes = [
  "Nothing is mentioned about the policy's history. The data it was last modified isn't also specified."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "If you have an account on this site, or have left comments, you can request to receive an exported file of the personal data we hold about you, including any data you have provided to us. You can also request that we erase any personal data we hold about you. This does not include any data we are obliged to keep for administrative, legal, or security purposes."
]

[rubric.data-breaches]
value = "no"
notes = [
  "Nothing is mentioned about data breaches. Also in 2016 hackers managed to access more than 20 million active accounts on Taobao."
]

[rubric.third-party-access]
value = "yes-unspecified"
notes = [
  "It's not stated that the service shares personal data with third parties. However, the embedded content from other websites behaves in the exact same way as if the visitor has visited the other website and these websites may collect personal data themselves using cookies and embedding additional third-party tracking."
]

[rubric.data-collection-reasoning]
value = "yes"
notes = [
  "The company collects only little data and reasonably explains the purposes. "
]

[rubric.noncritical-purposes]
value = "no"
notes = [
  "The amount of non-critical data collected is small, however, there are no options for opting-out"
]

[rubric.law-enforcement]
value = "unspecified"
notes = [
  "The policy does not mention anything about law enforcement access to personal data."
]

[rubric.list-collected]
value = "exhaustively"
notes = [
  "The company uses only absolute statements to describe the personal data it collects. "
]

[rubric.revision-notify]
value = "no"
notes = [
  "Nothing is mentioned about policies changes in the privacy policy. "
]
