name = "Windscribe"
description = "Windscribe is a private VPN service designed to protect users online."
slug = "windscribe"
hostnames = [ "windscribe.com" ]
sources = [ "https://windscribe.com/privacy" ]
contributors = [ "kqgWt" ]

[rubric.behavioral-marketing]
value = "no"

[rubric.security]
value = "yes"
citations = [
  "For the duration of your connection the following is stored in server's memory. This data is immediately discarded when you disconnect:\n\nOpenVPN/IKEv2 username\nTime of connection\nAmount of data transferred\nThe following data is stored in a central location:\n\nNumber of parallel connections at any given time to prevent rampant abuse and account sharing.\nA counter is incremented that stores total number of bytes downloaded/uploaded in a 30 day period.\nAnything that is not mentioned above is not stored."
]

[rubric.third-party-collection]
value = "no"

[rubric.history]
value = "last-modified"

[rubric.data-deletion]
value = "yes-automated"

[rubric.third-party-access]
value = "no"

[rubric.data-collection-reasoning]
value = "yes"

[rubric.noncritical-purposes]
value = "opt-out-all"

[rubric.law-enforcement]
value = "na"

[rubric.list-collected]
value = "exhaustively"

[rubric.revision-notify]
value = "yes"
