name = "World Population Review"
description = "This service is used to view the population data of any country."
slug = "world-population-review"
hostnames = [ "worldpopulationreview.com" ]
sources = [ "http://worldpopulationreview.com/privacy/" ]
contributors = [ "unbeatable101" ]

[rubric.behavioral-marketing]
value = "yes"

[rubric.security]
value = "somewhat"

[rubric.third-party-collection]
value = "yes"

[rubric.history]
value = "last-modified"
citations = [
  "This Privacy Policy was last updated on: Wednesday, July 22nd, 2017."
]

[rubric.data-deletion]
value = "yes-contact"
citations = [
  "We believe it is important to provide added protection for children online. We encourage parents and guardians to spend time online with their children to observe, participate in and/or monitor and guide their online activity. World Population Review does not knowingly collect any personally identifiable information from children under the age of 13. If a parent or guardian believes that World Population Review has in its database the personally-identifiable information of a child under the age of 13, please contact us immediately (using the contact in the first paragraph) and we will use our best efforts to promptly remove such information from our records."
]

[rubric.data-breaches]
value = "no"

[rubric.third-party-access]
value = "yes-specified-noncritical"

[rubric.data-collection-reasoning]
value = "mostly"

[rubric.noncritical-purposes]
value = "opt-out-some"

[rubric.law-enforcement]
value = "unspecified"

[rubric.list-collected]
value = "summarily"

[rubric.revision-notify]
value = "no"
