name = "YouTube"
description = "YouTube is a popular video sharing platform owned by Google."
hostnames = ["youtube.com"]
sort = 10 # optional sorting order
icon = "icons/youtube.png"
slug = "youtube"
parent = "google"