name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run tests
      run: npm test
    - uses: IgnusG/jest-report-action@v2.3.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}