name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: IgnusG/jest-report-action@v2
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}